name: fk_photos
description: A Photo Utils which is an extension for wechat_assets_picker
version: 2.1.0
homepage: https://github.com/flutter-fast-kit/fk_photos

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^4.2.1
  fk_action_sheet: ^2.0.0
  flutter_image_compress: ^1.1.0
  photo_view: ^0.12.0
  uuid: ^3.0.4
  wechat_assets_picker: ^6.1.1
  wechat_camera_picker: ^2.4.1
  path_provider: ^2.0.3