name: fk_photos
description: A Photo Utils which is an extension for wechat_assets_picker
version: 2.0.1
homepage: https://github.com/flutter-fast-kit/fk_photos

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^4.1.0
  fk_action_sheet: ^2.0.0
  flutter_image_compress: ^1.0.0
  photo_view: ^0.12.0
  uuid: ^3.0.4
  wechat_assets_picker: ^5.5.8
  wechat_camera_picker: ^2.2.0
  easy_localization: ^3.0.0
  path_provider: ^2.0.2