name: fk_photos
description: A Photo Utils which is an extension for wechat_assets_picker
version: 1.0.3
homepage: https://github.com/flutter-fast-kit/fk_photos

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^1.5.0
  fk_action_sheet: ^1.0.0
  flutter_image_compress: ^0.7.0
  photo_view: ^0.10.3
  uuid: ^2.2.2
  wechat_assets_picker: ^4.2.2
  wechat_camera_picker: ^1.3.1
  easy_localization: ^2.3.3
  path_provider: ^1.6.27