name: Publish to Pub.dev

on: create

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          flutter: true
          skipTests: true
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
